### PR TITLE
checkup: Re-order the functions

### PR DESCRIPTION
**Pull request by orelmisan**
Change the structure of checkup.go:
1. Main constructor function.
2. Checkup's methods
3. Helper constructors.
4. Helper functions.

### CODE REVIEW

**Review by EdDev — COMMENTED** [review]
Could you please also give a few words in the PR description on the "why"?

> Move constructor functions below Checkup methods.

I would expect to see the constructor of the object first.
From an order of reading, caller before callee, it fits better IMO.
Is there a specific reason you prefer the other way around?

**Comment by orelmisan** [comment]
IMO the reader of this file cares the most for the sequence of events that happens in Checkup's constructor and methods.
The rest of the constructors are mere helpers, and IMO add a lot of noise on the way to the main part of the file.

**Comment by orelmisan** [comment]
Rebase.

**Review by RamLavi — APPROVED** [review]
/lgtm

**Review by EdDev — APPROVED** [review]

**Pull request merged**
