### PR TITLE
design proposal: VM Latency Checkup Operator

### PR DESCRIPTION
**Pull request by orelmisan**
This design was rejected because it could not comply with the requirement to not involve the cluster-admin in the installation of the checkup - only a cluster-admin can install CRDs/operators.

Signed-off-by: Orel Misan <omisan@redhat.com>

### CODE REVIEW

**Comment by orelmisan** [comment]
Rebase
Changed Advantages section.
Added Disadvantages section.

**Comment by orelmisan** [comment]
Rebase.
Moved the design under the `rejected` directory.

**Comment by orelmisan** [comment]
@phoracek I've moved this design to the rejected directory.

**Review by phoracek — APPROVED** [review]

**Comment by EdDev** [comment]
I am not going to record rejected/freezed designs in the repo.
I think it is enough that they have been recorded in the PR.

If you think otherwise, please raise it in one of the discussions and we will re-open all design proposals that have been closed.

A decision has been taken to not proceed with any operator based solution.
We should revisit this and the other suggestions when the need will be raised .

**Pull request closed without merging**
