### PR TITLE
latency checkup, manifests: Remove example manifest

### PR DESCRIPTION
**Pull request by orelmisan**
Example manifests can be found in the checkup's README.md file.

Signed-off-by: Orel Misan <omisan@redhat.com>

### CODE REVIEW

**Comment by ormergi** [comment]
I think this should be merged after #83

**Comment by RamLavi** [comment]
what about https://github.com/kiagnose/kiagnose/blob/main/checkups/kubevirt-vm-latency/manifests/dev/kubevirt-vm-latency-checkup.yaml?

**Comment by orelmisan** [comment]
> what about https://github.com/kiagnose/kiagnose/blob/main/checkups/kubevirt-vm-latency/manifests/dev/kubevirt-vm-latency-checkup.yaml?

It is used to run the checkup without the framework for development purposes.
The echo checkup also have this.

We need to think what to do with them.

**Review by RamLavi — APPROVED** [review]
/lgtm

**Pull request merged**
