### PR TITLE
vmlatency, config: Reduce deprecation comments

### PR DESCRIPTION
**Pull request by ormergi**
Signed-off-by: Or Mergi <ormergi@redhat.com>

### CODE REVIEW

**Review by orelmisan — COMMENTED** [review]
Thank you for the PR @ormergi.

Does goland (the IDE) marks all the deprecated fields with a strike-though line?

**Review by RamLavi — APPROVED** [review]
/lgtm

**Comment by ormergi** [comment]
> Does the goland IDE marks all the deprecated fields with a strike-though line?

Yes

**Review by orelmisan — APPROVED** [review]
Thank you!

**Pull request merged**
