### PR TITLE
checkup: Name checkup SA after user-supplied CM

### PR DESCRIPTION
**Pull request by orelmisan**
Currently, the checkup ServiceAccount object's name is constant.
As a preliminary step to checkup execution in a target namespace,
name the checkup ServiceAccount with the following format:
`<user-supplied-CM-name>-sa`

Signed-off-by: Orel Misan <omisan@redhat.com>

~~Depends on PR #128.~~

### CODE REVIEW

**Comment by orelmisan** [comment]
E2E test fails because the measured latency is greater than the threshold.

**Comment by orelmisan** [comment]
> E2E test fails because the measured latency is greater than the threshold.

Fixed in PR #130.

**Review by EdDev — APPROVED** [review]
Thanks!

**Comment by orelmisan** [comment]
Rebase.

**Comment by orelmisan** [comment]
Rebase

**Review by EdDev — APPROVED** [review]

**Pull request merged**
