### PR TITLE
Revert "Kiagnose: bump k8s dependencies"

### PR DESCRIPTION
**Pull request by orelmisan**
Reverts kiagnose/kiagnose#204

The kiagnose library's K8s deps were updated, but not consumed by the vm latency checkup.

When the vm latency checkup tried to consume kiagnose with the newer K8s deps, and kubevirt deps, there was a conflict.

### CODE REVIEW

**Review by ormergi — COMMENTED** [review]
Thanks

**Review by ormergi — APPROVED** [review]

**Review by EdDev — COMMENTED** [review]
Can you please reason why it is reverted? For the future us...

**Comment by orelmisan** [comment]
> Can you please reason why it is reverted? For the future us...

Done.

**Review by EdDev — APPROVED** [review]
Thanks!

**Comment by EdDev** [comment]
Feel free to merge it once the tests pass.

**Pull request merged**
