### PR TITLE
vmlatency, config, tests: refactor

### PR DESCRIPTION
**Pull request by orelmisan**
Refactor VM latency's config tests, in order to improve code readability and enable simpler addition of tests in the future.

### CODE REVIEW

**Review by RamLavi — APPROVED** [review]
/lgtm

**Comment by orelmisan** [comment]
[Rebase](https://github.com/kiagnose/kiagnose/compare/72418914e6a81bf74f843d380aac2a17fec34130..7114dde0c3fdb7ea9b6969ec06e75d18dbcc8875)

**Comment by orelmisan** [comment]
[Rebase](https://github.com/kiagnose/kiagnose/compare/7114dde0c3fdb7ea9b6969ec06e75d18dbcc8875..5b4611fdea89bf7f41ff8d75bb1a2f69055fe8c1)

**Comment by orelmisan** [comment]
Something went wrong during the rebase.

**Comment by orelmisan** [comment]
[Change](https://github.com/kiagnose/kiagnose/compare/5b4611fdea89bf7f41ff8d75bb1a2f69055fe8c1..7d49133a2035cc2087774e9316bec71d25536a21):
1. Fixed problems caused by the rebase.
2. Changed commits order.

**Review by RamLavi — APPROVED** [review]
/lgtm

**Review by ormergi — CHANGES_REQUESTED** [review]
Regarding the last two commits, please change their titles so they won't be the same, something like:
```
 vmlatency, config, tests: Extract missing mandatory env vars tests
 vmlatency, config, tests: Extract invalid mandatory env vars tests
```
Or combine them together, in this case splitting to commit doesn't really help to review it (github mass up the diff anyways).

**Comment by orelmisan** [comment]
[Change](https://github.com/kiagnose/kiagnose/compare/7d49133a2035cc2087774e9316bec71d25536a21..9ae09ee58242e5ff7fd65b6a9bbeb1333fa46e67): Answered @ormergi's [comment](https://github.com/kiagnose/kiagnose/pull/166#pullrequestreview-1109251189).

**Review by ormergi — APPROVED** [review]
Thanks for the changes!

**Review by EdDev — APPROVED** [review]
Thanks

**Pull request merged**
