### PR TITLE
automation, e2e: Configure nodes network only on cluster creation

### PR DESCRIPTION
**Pull request by ormergi**
Following #152, this is a small fix that makes `--create-multi-node-cluster` configure the network only when the cluster is created.

Signed-off-by: Or Mergi <ormergi@redhat.com>

### CODE REVIEW

**Review by orelmisan — DISMISSED** [review]
Thank you @ormergi.

**Comment by ormergi** [comment]
@EdDev could you take a look?

**Review by EdDev — COMMENTED** [review]
>  e2e infra: Configure nodes network only on cluster creation 

Can you please change the topic to represent what changes more accurately?
Something like `automation, e2e:`.

**Comment by EdDev** [comment]
> Following #152, this is a small fix that makes `--create-multi-node-cluster` configure the network only when the cluster is created.

This information does not appear in the commit message.
But the real missing information is not this one, it is the reason for the change. This is not very clear (although makes sense), because there was surely something that went wrong that caused the need for this.

**Comment by ormergi** [comment]
> This information does not appear in the commit message. But the real missing information is not this one, it is the reason for the change. This is not very clear (although makes sense), because there was surely something that went wrong that caused the need for this.

@EdDev nothing went wrong actually, its just annoying that it asks for sudo password every time `--create-multi-node-cluster` is called.

**Comment by EdDev** [comment]
> > e2e infra: Configure nodes network only on cluster creation
> 
> Can you please change the topic to represent what changes more accurately? Something like `automation, e2e:`.

I see the PR changed, but I usually care more for the commit itself. Could you change it too?

**Comment by ormergi** [comment]
> I see the PR changed, but I usually care more for the commit itself. Could you change it too?

Done

**Comment by orelmisan** [comment]
> > I see the PR changed, but I usually care more for the commit itself. Could you change it too?
> 
> Done

@ormergi have you changed the commit message?
It is still empty.

**Comment by ormergi** [comment]
> > > I see the PR changed, but I usually care more for the commit itself. Could you change it too?
> > 
> > 
> > Done
> 
> @ormergi have you changed the commit message? It is still empty.

I changed the title.

**Comment by orelmisan** [comment]
@ormergi could you please answer @EdDev [comment](https://github.com/kiagnose/kiagnose/pull/160#issuecomment-1245012006)?

**Comment by ormergi** [comment]
> @ormergi could you please answer @EdDev [comment](https://github.com/kiagnose/kiagnose/pull/160#issuecomment-1245012006)?

I did, there is no actual problem.

**Review by orelmisan — APPROVED** [review]

**Pull request merged**
