### PR TITLE
vmlatency, e2e: Upgrade K8s version to v1.25.3

### PR DESCRIPTION
**Pull request by orelmisan**
Currently, we are checking the VM latency checkup against K8s v1.24.

Upgrade kind to the latest version v1.17.0 - thus upgrading K8s cluster to current stable v1.25.3.
Upgrade kubectl utility to v1.25.3 to match.

The k8s [client-go](https://github.com/kubernetes/client-go) package will be upgraded in a follow-up PR.
We should consider pining and mirroring kind [node images](https://hub.docker.com/r/kindest/node/), which are hosted on hub.docker.com.

### CODE REVIEW

**Comment by EdDev** [comment]
> We should consider pining and mirroring kind [node images](https://hub.docker.com/r/kindest/node/), which are hosted on hub.docker.com.

Agreed, the images should be pinned to assure we explicitly do the upgrade.
Although, I think that if we pin the kind version, we in practice pin the image as well (implicitly).

@ormergi , WDYT?

**Review by EdDev — APPROVED** [review]
Thanks!

We need to fix the local cache we use today.
We currently check the existence of a file, which does not include the version. This keeps old versions locally, avoiding their update.
We should have a follow up PR that changes the name of the d/l file, to include a version (and to compare against the expected file).

**Comment by orelmisan** [comment]
> Thanks!
> 
> We need to fix the local cache we use today. We currently check the existence of a file, which does not include the version. This keeps old versions locally, avoiding their update. We should have a follow up PR that changes the name of the d/l file, to include a version (and to compare against the expected file).

Agreed.

**Comment by ormergi** [comment]
> > We should consider pining and mirroring kind [node images](https://hub.docker.com/r/kindest/node/), which are hosted on hub.docker.com.
> 
> Agreed, the images should be pinned to assure we explicitly do the upgrade. Although, I think that if we pin the kind version, we in practice pin the image as well (implicitly).
> 
> @ormergi , WDYT?

That seems right, IMO the image should be explicitly set if one would like to use its own custom image or spin older version of k8s (e.g: 1.22 using the KIND release images).

**Review by ormergi — APPROVED** [review]
LGTM

**Pull request merged**
