### PR TITLE
automation, e2e: Format results

### PR DESCRIPTION
**Pull request by ormergi**
Format the checkup results and make them look human friendly.

Signed-off-by: Or Mergi <ormergi@redhat.com>

### CODE REVIEW

**Review by orelmisan — COMMENTED** [review]
Thank you for the PR @ormergi!
Can you please show in the PR description the output before and after this PR?

**Comment by EdDev** [comment]
> @EdDev well I need to rephrase it because using `-o yaml` is human readable sweat_smile
> my intention was to reduce noise from the results.

I find it useful to see the whole object. It does not make it too difficult to read it in its full form and adds the meta data information which may be useful when analyzing the result.
This is really borderline IMO.

**Comment by orelmisan** [comment]
I agree with @EdDev, I also think that `-o yaml` is fine for our needs.
Furthermore, the `sed` command's input is not very readable to the common person.

**Comment by ormergi** [comment]
Closing this PR since its nice to have and there is no agreement to accept it.

**Pull request closed without merging**
